import { useEffect, useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { SmokeSystem, type SmokeSpawn } from './smoke'
import { sharedGlowTexture } from './textures'
import { PAD } from './constants'
import { getLaunchTime, useLaunchStore } from '../launch/launchStore'
import {
  IGNITION_DURATION,
  MAX_STEP,
  MECO_ALTITUDE,
  altitudeAt,
  throttleAt,
} from '../launch/timeline'

const ROCKET_BASE_Y = PAD.padHeight + 7
const PAD_Y = PAD.padHeight

const COOL_SMOKE: [number, number, number] = [0.97, 0.96, 0.94]
const WARM_SMOKE: [number, number, number] = [1, 0.93, 0.85]

/**
 * Engine plume, exhaust lighting and the particle smoke generated by the
 * launch. Reads the launch clock every frame and never re-renders React.
 */
export function Exhaust() {
  const smoke = useMemo(() => new SmokeSystem(600), [])
  const flameRef = useRef<THREE.Group>(null)
  const coreRef = useRef<THREE.Mesh>(null)
  const midRef = useRef<THREE.Mesh>(null)
  const outerRef = useRef<THREE.Mesh>(null)
  const glowRef = useRef<THREE.Sprite>(null)
  const engineLight = useRef<THREE.PointLight>(null)
  const padLight = useRef<THREE.PointLight>(null)

  const glowTexture = useMemo(() => sharedGlowTexture(), [])
  const emit = useRef({ pad: 0, trail: 0, vent: 0, core: 0 })

  const phase = useLaunchStore((state) => state.phase)

  useEffect(() => {
    return () => smoke.reset()
  }, [smoke])

  useEffect(() => {
    if (phase === 'idle') smoke.reset()
  }, [phase, smoke])

  useFrame((_, rawDelta) => {
    const dt = Math.min(rawDelta, MAX_STEP)
    const t = getLaunchTime()
    const altitude = altitudeAt(t)
    // Thrust cuts off over the last stretch of the burn.
    const throttle =
      throttleAt(t) *
      (1 - THREE.MathUtils.smoothstep(altitude, MECO_ALTITUDE - 220, MECO_ALTITUDE))
    const engineY = ROCKET_BASE_Y + altitude
    const flicker =
      1 +
      0.13 * Math.sin(t * 43.7) +
      0.07 * Math.sin(t * 97.3 + 1.7) +
      0.05 * Math.sin(t * 211.1 + 0.4)

    // --- Plume ------------------------------------------------------------
    const flame = flameRef.current
    if (flame) {
      flame.visible = throttle > 0.02
      flame.position.y = engineY - 0.9
    }
    const intensity = throttle * flicker
    if (coreRef.current) {
      coreRef.current.scale.set(
        1.2 + intensity * 0.7,
        17 * intensity,
        1.2 + intensity * 0.7,
      )
    }
    if (midRef.current) {
      midRef.current.scale.set(
        2 + intensity * 1.1,
        27 * intensity,
        2 + intensity * 1.1,
      )
    }
    if (outerRef.current) {
      outerRef.current.scale.set(
        3 + intensity * 2,
        41 * intensity,
        3 + intensity * 2,
      )
    }
    if (glowRef.current) {
      const glow = 7 + intensity * 15
      glowRef.current.scale.set(glow, glow, 1)
      glowRef.current.position.y = engineY - 1.4
      ;(glowRef.current.material as THREE.SpriteMaterial).opacity =
        0.28 + intensity * 0.32
    }

    // --- Exhaust lighting -------------------------------------------------
    if (engineLight.current) {
      engineLight.current.position.set(0, engineY - 2, 0)
      engineLight.current.intensity = 26000 * intensity
    }
    if (padLight.current) {
      padLight.current.intensity = 2600 * intensity * Math.max(0, 1 - altitude / 260)
    }

    // --- Smoke emission ---------------------------------------------------
    const emitter = emit.current
    const spawn = (spec: SmokeSpawn) => smoke.spawn(spec)

    if (t > 0 && t < IGNITION_DURATION + 3) {
      // Ignition: a violent burst hugging the pad that spreads outward.
      emitter.pad += dt * (74 * throttle + 12)
      while (emitter.pad >= 1) {
        emitter.pad -= 1
        const angle = Math.random() * Math.PI * 2
        const radius = 4 + Math.random() * 13
        const cos = Math.cos(angle)
        const sin = Math.sin(angle)
        spawn({
          position: [cos * radius, PAD_Y + 1 + Math.random() * 3, sin * radius],
          velocity: [cos * (5 + Math.random() * 8), 2 + Math.random() * 4, sin * (5 + Math.random() * 8)],
          spread: 2.5,
          size: [8, 42 + Math.random() * 16],
          life: [5, 9],
          alpha: 0.42,
          color: Math.random() < 0.25 ? WARM_SMOKE : COOL_SMOKE,
          drag: 0.85,
          buoyancy: 1.4,
          spin: 0.3,
        })
      }
      emitter.core += dt * 40 * throttle
      while (emitter.core >= 1) {
        emitter.core -= 1
        spawn({
          position: [
            (Math.random() - 0.5) * 7,
            engineY - 4 - Math.random() * 8,
            (Math.random() - 0.5) * 7,
          ],
          velocity: [(Math.random() - 0.5) * 5, 3 + Math.random() * 5, (Math.random() - 0.5) * 5],
          spread: 2,
          size: [5, 26],
          life: [3, 6],
          alpha: 0.55,
          color: WARM_SMOKE,
          drag: 1.1,
          buoyancy: 2.2,
          spin: 0.4,
        })
      }
    } else if (t >= IGNITION_DURATION + 3 && altitude < 420) {
      // Ascent: residual ground cloud plus a trail that stays behind.
      emitter.pad += dt * 16 * Math.max(0, 1 - altitude / 420)
      while (emitter.pad >= 1) {
        emitter.pad -= 1
        const angle = Math.random() * Math.PI * 2
        const radius = 6 + Math.random() * 20
        spawn({
          position: [
            Math.cos(angle) * radius,
            PAD_Y + 2 + Math.random() * 8,
            Math.sin(angle) * radius,
          ],
          velocity: [Math.cos(angle) * 3, 1.5 + Math.random() * 2, Math.sin(angle) * 3],
          spread: 1.6,
          size: [14, 52],
          life: [6, 11],
          alpha: 0.34,
          color: COOL_SMOKE,
          drag: 0.7,
          buoyancy: 1.1,
          spin: 0.2,
        })
      }
    }

    if (t >= IGNITION_DURATION && altitude < 5200) {
      emitter.trail += dt * 62
      while (emitter.trail >= 1) {
        emitter.trail -= 1
        const angle = Math.random() * Math.PI * 2
        const radius = 2 + Math.random() * 6
        spawn({
          position: [
            Math.cos(angle) * radius,
            engineY - 2 - Math.random() * 10,
            Math.sin(angle) * radius,
          ],
          velocity: [
            Math.cos(angle) * (2 + Math.random() * 4),
            -2 + Math.random() * 2,
            Math.sin(angle) * (2 + Math.random() * 4),
          ],
          spread: 1.5,
          size: [6, 36],
          life: [3, 5.5],
          alpha: 0.3,
          color: Math.random() < 0.5 ? WARM_SMOKE : COOL_SMOKE,
          drag: 1.5,
          buoyancy: 1.8,
          spin: 0.5,
        })
      }
    }

    if (t <= 0) {
      // Cryogenic venting while the vehicle sits on the pad.
      emitter.vent += dt * 7
      while (emitter.vent >= 1) {
        emitter.vent -= 1
        const angle = Math.random() * Math.PI * 2
        const radius = 4 + Math.random() * 6
        spawn({
          position: [
            Math.cos(angle) * radius,
            PAD_Y + 1,
            Math.sin(angle) * radius,
          ],
          velocity: [Math.cos(angle) * 1.2, 2.4, Math.sin(angle) * 1.2],
          spread: 0.8,
          size: [2.5, 12],
          life: [3, 5],
          alpha: 0.24,
          color: COOL_SMOKE,
          drag: 0.9,
          buoyancy: 1.6,
          spin: 0.3,
        })
      }
    }

    smoke.update(dt)
  })

  return (
    <>
      <primitive object={smoke.object} />

      <group ref={flameRef} visible={false}>
        <mesh ref={outerRef} position={[0, -20, 0]}>
          <coneGeometry args={[1, 1, 20, 1, true]} />
          <meshBasicMaterial
            color="#ff7a1e"
            transparent
            opacity={0.32}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            side={THREE.DoubleSide}
            toneMapped={false}
          />
        </mesh>
        <mesh ref={midRef} position={[0, -13, 0]}>
          <coneGeometry args={[1, 1, 18, 1, true]} />
          <meshBasicMaterial
            color="#ffb347"
            transparent
            opacity={0.55}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            side={THREE.DoubleSide}
            toneMapped={false}
          />
        </mesh>
        <mesh ref={coreRef} position={[0, -8, 0]}>
          <coneGeometry args={[1, 1, 14, 1, true]} />
          <meshBasicMaterial
            color="#fff6d5"
            transparent
            opacity={0.95}
            blending={THREE.AdditiveBlending}
            depthWrite={false}
            side={THREE.DoubleSide}
            toneMapped={false}
          />
        </mesh>
      </group>

      <sprite ref={glowRef} position={[0, 0, 0]}>
        <spriteMaterial
          map={glowTexture}
          transparent
          opacity={0.5}
          blending={THREE.AdditiveBlending}
          depthWrite={false}
          toneMapped={false}
        />
      </sprite>

      <pointLight
        ref={engineLight}
        color="#ff9a3c"
        intensity={0}
        distance={600}
        decay={2}
      />
      <pointLight
        ref={padLight}
        position={[0, PAD_Y + 3, 0]}
        color="#ff7a2a"
        intensity={0}
        distance={420}
        decay={2}
      />
    </>
  )
}
